export default {
  courseObj: null,
  engagedCourses: null,
  Categories: null,
  Announcements: null,
  Resources: null,
  Polls: null,
  Surveys: null,
  savedSurveys: null,
  scheduledSurveys: null,
  Tickets: null,
  Groups: null,
  Admins: null,
  Assets: null,
  Leaders: null,
  Users: null,
  Analytics: null,
  ResourceCategories: null,
  ScoreCard: null,
  AssignedUsers: null
};
